[package]
name = "blue-archive-decoder"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
flatbuffers = { version = "25.9.23", features = ["serde"] }
paste = "1.0.15"
regex = "1.12.2"
serde = { version = "1.0.228", features = ["derive"] }
wasm-bindgen = "0.2.106"
