[package]
name = "blue-archive-decoder"
version = "0.1.0"
edition = "2024"

[dependencies]
flatbuffers = { version = "25.9.23", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
